### ISSUE TITLE
Update for 1.17.1

### ISSUE THREAD

**Issue by k4tana9** [ISenseHostility/Pingot#1]
I’m currently working on a mod pack that is going to combine vanilla-like mods together into one package. Only problem is all the mods are for 1.17.1. Is there any chance of you updating this mod? I think it’s a cool and funny one to add to my collection.

**Comment by ISenseHostility** [comment]
Sure, I'll update it in a couple days.

**Comment by ISenseHostility** [comment]
The file is currently processing so it should be available for download in a couple minutes!

**Comment by k4tana9** [comment]
> Sure, I'll update it in a couple days.

Thx! Very happy to use it
